cargo-features = ["profile-rustflags", "trim-paths"]

[package]
name = "OhMyKeymint"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0-or-later"

[[bin]]
name = "keymint"
path = "src/main.rs"

# [lib]
# name = "ohmykeymint"
# path = "src/lib.rs"
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.21.1"
syscalls = "0.6.15"
kmr-derive = { path = "derive" }
kmr-common = { path = "common" }
kmr-crypto-boring = { path = "boringssl" }
kmr-ta = { path = "ta" }
kmr-wire = { path = "wire" }
libc = "0.2.176"
prost = "0.14.1"
prost-types = "0.14.1"
hex = "0.4.3"
log4rs = "1.4.0"
log = "0.4.28"
rsbinder = { version = "0.4.2", features = ["android_12_plus"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
anyhow = "1.0.100"
async-trait = "0.1.89"
tokio = { version = "1.47.1", features = ["macros", "libc"] }
lazy_static = "1.5.0"
thiserror = "2.0.17"
serde = "1.0.228"
x509-cert = "0.2.5"
watchdog_rs = "*"
nix = { version = "0.30.1", features = ["mman"] }
rsproperties = { version = "0.2.2", features = ["builder"] }
libsqlite3-sys = "0.35.0"
rand = "0.9.2"
der = "0.7.10"
toml = "0.9.8"
regex = "1.12.2"
hotwatch = "0.5.0"

[target.'cfg(target_os = "linux")'.dependencies]
rsproperties-service = "*"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15.1"


[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
debuginfo = 0       # Disable debug info
trim-paths = "all"

[workspace]
members = [
  "boringssl",
  "common",
  "derive",
  "ta",
  "tests",
  "wire",
  "watchdog",
  "rsproperties-service",
]

[patch.crates-io]
kmr-derive = { path = "derive" }
kmr-common = { path = "common" }
kmr-crypto-boring = { path = "boringssl" }
kmr-ta = { path = "ta" }
kmr-tests = { path = "tests" }
kmr-wire = { path = "wire" }
watchdog_rs = { path = "watchdog" }
rsproperties-service = { path = "rsproperties-service" }

[build-dependencies]
prost-build = "0.14.1"
rsbinder-aidl = "0.4.3"
